baseURL = "https://ilang.ai/blog/"
languageCode = "en"
title = "I-Lang Blog"
publishDir = "../blog"
enableRobotsTXT = false

[taxonomies]
  tag = "tags"

[params]
  description = "Building the native language of artificial intelligence. Stories from the I-Lang protocol team."
  author = "Long Quan Zhu"
  mainSite = "https://ilang.ai"

[related]
  includeNewer = true
  threshold = 50
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"
    lineNos = false

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
